#!/bin/bash

# create .eslintrc
rm -rf ".eslintrc"
echo '{
    "extends":"react-app"
}' > .eslintrc

# create .babelrc
rm -rf ".babelrc"
echo '{
    "presets": ["@babel/preset-react", "@babel/preset-env"],
    "plugins": [["@babel/plugin-proposal-class-properties", { "loose": true }]]    
}' > .babelrc

# remove src directory and create
rm -rf src
mkdir src
cd src
mkdir $1
cd $1

# create sample component
rm -rf "SampleComponent.js"
echo '
import React from "react";

class SampleComponent extends React.Component {
  a_class_field = "Hello world";

  render() {
    return <div>{this.a_class_field}</div>;
  }
}

export default SampleComponent;
' > SampleComponent.js

# create index.js
rm -rf "index.js"
echo '
import SampleComponent from "./SampleComponent";
export { SampleComponent};
' > index.js

cd ..

# create index.js
rm -rf "index.js"
echo '
import React from "react";
import { render } from "react-dom";
import SampleComponent from "./'$1'/SampleComponent";

const App = () => (
  <SampleComponent/>
);

render(<App />, document.getElementById("root"));
' > index.js

cd ..

# create package.json
rm -rf "package.json"
echo '
{
  "name": "'$1'",
  "version": "0.1.0",
  "main": "'$1'/index.js",
  "module": "'$1'/index.js",
  "files": [
    "'$1'"
  ],
  "scripts": {
    "start": "react-scripts start",
    "build-examples": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject",
    "build": "rimraf '$1'  && NODE_ENV=production babel src/'$1' --out-dir '$1' --source-maps --copy-files --ignore __tests__,spec.js,test.js,__snapshots__",
    "watch":"watch '"'"'npm run build'"'"' ./src/'$1'"
  },
  "dependencies": {
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-scripts": "^2.1.3"
  },  
  "devDependencies": {
    "@babel/cli": "^7.2.3",
    "@babel/core": "^7.2.2",
    "@babel/plugin-proposal-class-properties": "^7.2.3",
    "@babel/preset-env": "^7.2.3",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "^8.0.4",
    "rimraf": "^2.6.3",
    "watch": "^1.0.2"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}
' > package.json

rm -rf node_modules
rm -rf package-lock.json
npm install
npm run build